# Generated by Django 4.1 on 2022-08-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='studid',
        ),
    ]
