# Generated by Django 4.1 on 2022-08-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salesrecord',
            fields=[
                ('region', models.TextField(blank=True, db_column='Region', null=True)),
                ('country', models.TextField(blank=True, db_column='Country', null=True)),
                ('item_type', models.TextField(blank=True, db_column='Item Type', null=True)),
                ('sales_channel', models.TextField(blank=True, db_column='Sales Channel', null=True)),
                ('order_id', models.IntegerField(blank=True, db_column='Order ID', primary_key=True, serialize=False)),
                ('units_sold', models.IntegerField(blank=True, db_column='Units Sold', null=True)),
                ('unit_price', models.FloatField(blank=True, db_column='Unit Price', null=True)),
                ('unit_cost', models.FloatField(blank=True, db_column='Unit Cost', null=True)),
                ('total_revenue', models.FloatField(blank=True, db_column='Total Revenue', null=True)),
                ('total_cost', models.FloatField(blank=True, db_column='Total Cost', null=True)),
                ('total_profit', models.FloatField(blank=True, db_column='Total Profit', null=True)),
            ],
            options={
                'db_table': 'salesrecord',
                'managed': False,
            },
        ),
    ]
